/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.craftify.backend.api;

import com.craftify.backend.api.model.ItemsBatchDeletePost200Response;
import com.craftify.backend.api.model.ItemsBatchDeletePostRequest;
import com.craftify.backend.api.model.ProblemDetail;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@Validated
@Tag(name = "Items", description = "the Items API")
public interface ItemsBatchDeleteApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_ITEMS_BATCH_DELETE_POST = "/items:batch-delete";

    /**
     * POST /items:batch-delete : Bulk delete items by id
     *
     * @param itemsBatchDeletePostRequest (required)
     * @return Result (status code 200)
     * or Problem Details (RFC-7807) (status code 400)
     */
    @Operation(
            operationId = "itemsBatchDeletePost",
            summary = "Bulk delete items by id",
            tags = {"Items"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Result", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ItemsBatchDeletePost200Response.class)),
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ItemsBatchDeletePost200Response.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Problem Details (RFC-7807)", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetail.class)),
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
                    })
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = ItemsBatchDeleteApi.PATH_ITEMS_BATCH_DELETE_POST,
            produces = {"application/json", "application/problem+json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<ItemsBatchDeletePost200Response> itemsBatchDeletePost(
            @Parameter(name = "ItemsBatchDeletePostRequest", description = "", required = true) @Valid @RequestBody ItemsBatchDeletePostRequest itemsBatchDeletePostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"deleted\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/problem+json"))) {
                    String exampleString = "Custom MIME type example not yet supported: application/problem+json";
                    ApiUtil.setExampleResponse(request, "application/problem+json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
