spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER:https://dev-f5ge1-8v.us.auth0.com/}
          audiences:
            - ${AUTH0_AUDIENCE:https://app.craftify.com/}

server:
  max-http-request-header-size: 100MB
  shutdown: graceful
  port: 8080
  compression:
    enabled: true
    mime-types: text/xml,text/plain,application/json
    min-response-size: 1024

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha

app:
  security:
    disabled: true
  cors:
    allowed-origins:
      - http://localhost:5173
      - https://kalpak44.github.io/craftify

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.fasterxml.jackson.databind: INFO
