name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/**'

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image tags
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          # Use ref_name (branch or tag without refs/heads/)
          BRANCH_NAME="${GITHUB_REF_NAME}"
          # Sanitize branch for Docker tag: lowercase and replace invalid chars with '-'
          SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9._-]#-#g')
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "branch=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            kalpak44/craftify-app:sha-${{ steps.vars.outputs.short_sha }}
            kalpak44/craftify-app:branch-${{ steps.vars.outputs.branch }}
            kalpak44/craftify-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

